import { loadJSON, saveJSON } from "../utils/storage.js";
import { ollamaGenerate, ollamaChat } from "./ollama.js";
import { storeDocument } from "./vectordb.js";

// ============================================
// v2.0 — Automated Paper Summarization via Ollama
// Uses local LLM to summarize and extract insights
// ============================================

interface PaperSummary {
  paperId: string;
  title: string;
  summary: string;
  keyInsights: string[];
  methodology: string;
  results: string;
  relevanceToGoal: string;
  readingTime: string;
  generatedAt: string;
  model: string;
}

export async function summarizePaper(paperId: string): Promise<object> {
  const papers = loadJSON<any[]>("papers.json", []);
  const paper = papers.find((p: any) => p.id === paperId);

  if (!paper) {
    return { error: `Paper '${paperId}' not found. Use get_paper_queue to see available papers.` };
  }

  // Build context from paper data
  const paperContext = [
    `Title: ${paper.title}`,
    `Authors: ${paper.authors}`,
    paper.notes ? `Notes: ${paper.notes}` : "",
    paper.keyInsights?.length ? `Key insights: ${paper.keyInsights.join("; ")}` : "",
    paper.architectureNotes ? `Architecture: Input=${paper.architectureNotes.input || "?"}, Representation=${paper.architectureNotes.representation || "?"}, Latent=${paper.architectureNotes.latentSpace || "?"}, Objective=${paper.architectureNotes.objective || "?"}, Uncertainty=${paper.architectureNotes.uncertaintyModel || "?"}` : "",
  ].filter(Boolean).join("\n");

  const prompt = `You are a computational biology / ML research assistant. Summarize this paper concisely for a graduate student studying VAEs, GNNs, and single-cell biology for the Lotfollahi lab.

PAPER INFORMATION:
${paperContext}

Provide your summary in the following format:

## Summary (2-3 sentences)
[concise summary]

## Key Insights (bullet points)
- [insight 1]
- [insight 2]
- [insight 3]

## Methodology
[brief methodology description]

## Results
[key findings]

## Relevance to Comp-Bio + ML Goals
[why this matters for the student's research direction]

## Estimated Deep-Read Time
[estimate based on complexity]`;

  try {
    const response = await ollamaGenerate(prompt, {
      system: "You are a precise scientific summarizer. Be concise but comprehensive. Always connect findings to computational biology applications.",
      temperature: 0.3,
    });

    // Parse sections
    const sections = parseSections(response);

    const summary: PaperSummary = {
      paperId,
      title: paper.title,
      summary: sections.summary || response.slice(0, 300),
      keyInsights: sections.keyInsights || [],
      methodology: sections.methodology || "",
      results: sections.results || "",
      relevanceToGoal: sections.relevance || "",
      readingTime: sections.readingTime || "30-45 minutes",
      generatedAt: new Date().toISOString(),
      model: "ollama-local",
    };

    // Store summary
    const summaries = loadJSON<PaperSummary[]>("paper-summaries.json", []);
    const existingIdx = summaries.findIndex((s) => s.paperId === paperId);
    if (existingIdx >= 0) {
      summaries[existingIdx] = summary;
    } else {
      summaries.push(summary);
    }
    saveJSON("paper-summaries.json", summaries);

    // Index in vector DB for later retrieval
    try {
      await storeDocument(
        "study-papers",
        `paper-summary-${paperId}`,
        `${paper.title}. ${summary.summary} Key insights: ${summary.keyInsights.join(". ")}`,
        { paperId, title: paper.title, type: "paper-summary" }
      );
    } catch {
      // ChromaDB not available
    }

    return {
      ...summary,
      rawResponse: response,
      note: "Summary generated by local Ollama model. Verify key claims against the actual paper.",
    };
  } catch (err: any) {
    return { error: `Summarization failed: ${err.message}` };
  }
}

export async function summarizeFromAbstract(
  title: string,
  abstract: string,
  authors?: string
): Promise<object> {
  const prompt = `Summarize this research paper for a computational biology + ML graduate student:

Title: ${title}
${authors ? `Authors: ${authors}` : ""}

Abstract:
${abstract}

Provide:
1. One-sentence TL;DR
2. Key innovation (what's new)
3. Core method (brief)
4. Main result
5. Relevance to: VAEs, GNNs, single-cell biology, perturbation prediction
6. Should I read the full paper? (yes/no with reason)`;

  try {
    const response = await ollamaGenerate(prompt, {
      system: "Be concise and actionable. Focus on what matters for a comp-bio ML researcher.",
      temperature: 0.3,
    });

    return {
      title,
      analysis: response,
      generatedBy: "ollama-local",
      note: "Quick analysis from abstract only. Full paper read recommended for high-relevance papers.",
    };
  } catch (err: any) {
    return { error: `Analysis failed: ${err.message}` };
  }
}

export async function generateKeyInsightsFromPaper(paperId: string): Promise<object> {
  const papers = loadJSON<any[]>("papers.json", []);
  const paper = papers.find((p: any) => p.id === paperId);

  if (!paper) {
    return { error: `Paper '${paperId}' not found.` };
  }

  const context = [
    `Title: ${paper.title}`,
    paper.notes ? `Your notes: ${paper.notes}` : "",
    paper.keyInsights?.length ? `Existing insights: ${paper.keyInsights.join("; ")}` : "",
  ].filter(Boolean).join("\n");

  const messages = [
    {
      role: "user",
      content: `Based on this paper, generate study questions and spaced repetition items I should add to my review system:

${context}

Generate:
1. 3-5 conceptual questions to test my understanding
2. 3-5 key facts/formulas to memorize via spaced repetition  
3. 2-3 implementation ideas connecting this to my projects
4. 1 "connection insight" linking this to other topics I'm studying (VAEs, GNNs, single-cell bio)`,
    },
  ];

  try {
    const result = await ollamaChat(messages, {
      system: "You are a study coach creating active recall material from research papers. Make items specific and testable.",
      temperature: 0.5,
    });

    return {
      paperId,
      title: paper.title,
      studyMaterial: result.response,
      model: result.model,
      suggestion: "Use add_revision to add the spaced repetition items, and save_insight to store the connections.",
    };
  } catch (err: any) {
    return { error: `Failed to generate insights: ${err.message}` };
  }
}

export async function comparePapers(paperIds: string[]): Promise<object> {
  const papers = loadJSON<any[]>("papers.json", []);
  const selectedPapers = paperIds
    .map((id) => papers.find((p: any) => p.id === id))
    .filter(Boolean);

  if (selectedPapers.length < 2) {
    return { error: "Need at least 2 valid paper IDs to compare." };
  }

  const paperDescs = selectedPapers.map((p: any, i: number) =>
    `Paper ${i + 1}: "${p.title}" by ${p.authors}${p.notes ? `. Notes: ${p.notes}` : ""}`
  ).join("\n\n");

  try {
    const response = await ollamaGenerate(
      `Compare these papers side by side for a comp-bio ML researcher:\n\n${paperDescs}\n\nProvide:\n1. Comparison table (method, data, key contribution)\n2. How they complement each other\n3. Which is more relevant for perturbation prediction research\n4. Suggested reading order`,
      {
        system: "Create a structured comparison. Be specific about methodological differences.",
        temperature: 0.4,
      }
    );

    return {
      papers: selectedPapers.map((p: any) => ({ id: p.id, title: p.title })),
      comparison: response,
      model: "ollama-local",
    };
  } catch (err: any) {
    return { error: `Comparison failed: ${err.message}` };
  }
}

// --- Helpers ---

function parseSections(text: string): Record<string, any> {
  const result: Record<string, any> = {};

  const summaryMatch = text.match(/##\s*Summary[\s\S]*?\n([\s\S]*?)(?=##|$)/i);
  if (summaryMatch) result.summary = summaryMatch[1].trim();

  const insightsMatch = text.match(/##\s*Key Insights[\s\S]*?\n([\s\S]*?)(?=##|$)/i);
  if (insightsMatch) {
    result.keyInsights = insightsMatch[1]
      .split("\n")
      .filter((l: string) => l.trim().startsWith("-"))
      .map((l: string) => l.replace(/^-\s*/, "").trim());
  }

  const methodMatch = text.match(/##\s*Methodology[\s\S]*?\n([\s\S]*?)(?=##|$)/i);
  if (methodMatch) result.methodology = methodMatch[1].trim();

  const resultsMatch = text.match(/##\s*Results[\s\S]*?\n([\s\S]*?)(?=##|$)/i);
  if (resultsMatch) result.results = resultsMatch[1].trim();

  const relevanceMatch = text.match(/##\s*Relevance[\s\S]*?\n([\s\S]*?)(?=##|$)/i);
  if (relevanceMatch) result.relevance = relevanceMatch[1].trim();

  const timeMatch = text.match(/##\s*Estimated[\s\S]*?\n([\s\S]*?)(?=##|$)/i);
  if (timeMatch) result.readingTime = timeMatch[1].trim();

  return result;
}
